package parctice;

public class test3 {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		String tempSix="浊心斯卡蒂"
				+ "Skadi the Corrupting Heart "
				+ "凯尔希 "
				+ "Kal'tsit "
				+ "歌蕾蒂娅 "
				+ "Gladiia "
				+ "异客 "
				+ "Passenger "
				+ "灰烬 "
				+ "Ash "
				+ "夕 "
				+ "Dusk "
				+ "嵯峨 "
				+ "Saga "
				+ "空弦 "
				+ "Archetto "
				+ "山 "
				+ "Mountain "
				+ "迷迭香 "
				+ "Rosmontis "
				+ "泥岩 "
				+ "Mudrock "
				+ "瑕光 "
				+ "Blemishine "
				+ "史尔特尔 "
				+ "Surtr "
				+ "森蚺 "
				+ "Eunectes "
				+ "棘刺 "
				+ "Thorns "
				+ "铃兰 "
				+ "Suzuran "
				+ "早露 "
				+ "Роса "
				+ "打不溜 "
				+ "W "
				+ "温蒂 "
				+ "Weedy "
				+ "傀影 "
				+ "Phantom "
				+ "风笛 "
				+ "Bagpipe "
				+ "刻俄柏 "
				+ "Ceobe "
				+ "年 "
				+ "Nian "
				+ "阿 "
				+ "Aak "
				+ "煌 "
				+ "Blaze "
				+ "莫斯提马 "
				+ "Mostima "
				+ "麦哲伦 "
				+ "Magallan "
				+ "赫拉格 "
				+ "Hellagur "
				+ "黑 "
				+ "Schwarz "
				+ "陈 "
				+ "Ch'en "
				+ "斯卡蒂 "
				+ "Skadi "
				+ "银灰 "
				+ "SilverAsh "
				+ "塞雷娅 "
				+ "Saria "
				+ "星熊 "
				+ "Hoshiguma "
				+ "夜莺 "
				+ "Nightingale "
				+ "闪灵 "
				+ "Shining "
				+ "安洁莉娜 "
				+ "Angelina "
				+ "艾雅法拉 "
				+ "Eyjafjalla "
				+ "伊芙利特 "
				+ "Ifrit "
				+ "推进之王 "
				+ "Siege "
				+ "能天使 "
				+ "Exusiai "
				;
		String a[]=tempSix.split("[a-zA-Z']+[ ]+[a-zA-Z]*[ ]*[a-zA-Z]*[ ]*[a-zA-Z]*[ ]*");
		/*[[\\w]+[\\s]*]+*/
		for(String x:a) {
			System.out.println(x+" ");
		}
	}

}
